### ISSUE TITLE
Project installation/setup overview

### ISSUE THREAD

**Issue by InLaw** [cript0nauta/pynixify#39]
is there a way to show/ inspect the whole installed setup/packages with versions (and hashes)
regrading 
- linux/OS packages
- language packages for  python c++ js java (which could be related to a package as dependency)

**Comment by cript0nauta** [comment]
Yes there is a way, this feature is provided by Nix itself. You can query the closure of an output, i.e. the list of all transitive dependencies. If you're using the `pynixify/shell.nix` file, you can do something like this:

```
$ nix-store -qR $(nix-build pynixify/shell.nix -A buildInputs)
```

This will first build the python environment with all the specified dependencies, and then it wil print the contents of the whole closure. Does this answer your question?

**Comment by InLaw** [comment]
[nix-tree](https://github.com/utdemir/nix-tree )
- shows the dependencies as well and (reverse [for a specific pkg])

(ok for now)

**Comment by cript0nauta** [comment]
I didn't know about nix-tree, it looks great! :smile:
